"""In-memory адаптеры.

Используются для unit-тестов, MVP и локальной разработки. Хранилище —
plain dict под anyio-блокировкой для потокобезопасности.
"""

from sdn_controller.adapters.memory.repositories import (
    InMemoryAddressPoolRepository,
    InMemoryAuditEventRepository,
    InMemoryBgpPeerRepository,
    InMemoryEnrollmentTokenRepository,
    InMemoryFloatingIpRepository,
    InMemoryGatewayBondRepository,
    InMemoryHealthMonitorRepository,
    InMemoryIpAllocationRepository,
    InMemoryLbListenerRepository,
    InMemoryLbMemberRepository,
    InMemoryLbPoolRepository,
    InMemoryLoadBalancerRepository,
    InMemoryLogicalPortRepository,
    InMemoryNetworkRepository,
    InMemoryNodeRepository,
    InMemoryNodeSnapshotRepository,
    InMemoryObservedStateRepository,
    InMemoryOperationRepository,
    InMemoryOutboxRepository,
    InMemoryProjectMemberRepository,
    InMemoryProjectQuotaRepository,
    InMemoryProjectRepository,
    InMemoryQosPolicyRepository,
    InMemoryResourceSnapshotRepository,
    InMemoryRetentionPolicyRepository,
    InMemoryRouterRepository,
    InMemorySecurityGroupMemberRepository,
    InMemorySecurityGroupRepository,
    InMemorySecurityPolicyRepository,
    InMemoryServiceAccountRepository,
    InMemoryServiceObjectRepository,
    InMemoryServiceTokenRepository,
    InMemoryTrunkPortRepository,
    InMemoryWebhookSubscriptionRepository,
)

__all__ = [
    "InMemoryAddressPoolRepository",
    "InMemoryAuditEventRepository",
    "InMemoryBgpPeerRepository",
    "InMemoryEnrollmentTokenRepository",
    "InMemoryFloatingIpRepository",
    "InMemoryGatewayBondRepository",
    "InMemoryHealthMonitorRepository",
    "InMemoryIpAllocationRepository",
    "InMemoryLbListenerRepository",
    "InMemoryLbMemberRepository",
    "InMemoryLbPoolRepository",
    "InMemoryLoadBalancerRepository",
    "InMemoryLogicalPortRepository",
    "InMemoryNetworkRepository",
    "InMemoryNodeRepository",
    "InMemoryNodeSnapshotRepository",
    "InMemoryObservedStateRepository",
    "InMemoryOperationRepository",
    "InMemoryOutboxRepository",
    "InMemoryProjectMemberRepository",
    "InMemoryProjectQuotaRepository",
    "InMemoryProjectRepository",
    "InMemoryQosPolicyRepository",
    "InMemoryResourceSnapshotRepository",
    "InMemoryRetentionPolicyRepository",
    "InMemoryRouterRepository",
    "InMemorySecurityGroupMemberRepository",
    "InMemorySecurityGroupRepository",
    "InMemorySecurityPolicyRepository",
    "InMemoryServiceAccountRepository",
    "InMemoryServiceObjectRepository",
    "InMemoryServiceTokenRepository",
    "InMemoryTrunkPortRepository",
    "InMemoryWebhookSubscriptionRepository",
]
