"""SQLAlchemy persistence adapter.

The same module backs both SQLite (MVP default) and PostgreSQL (future): only
the database URL — and, optionally, engine-level args — differ. Repository
classes implement the same Protocols as the in-memory adapter so use cases are
unaware of the swap.
"""

from sdn_controller.adapters.sql.engine import build_engine, build_sessionmaker
from sdn_controller.adapters.sql.models import Base
from sdn_controller.adapters.sql.repositories import (
    SqlAddressPoolRepository,
    SqlAuditEventRepository,
    SqlBgpPeerRepository,
    SqlEnrollmentTokenRepository,
    SqlFloatingIpRepository,
    SqlGatewayBondRepository,
    SqlHealthMonitorRepository,
    SqlIpAllocationRepository,
    SqlLbListenerRepository,
    SqlLbMemberRepository,
    SqlLbPoolRepository,
    SqlLoadBalancerRepository,
    SqlLogicalPortRepository,
    SqlNetworkRepository,
    SqlNodeRepository,
    SqlNodeSnapshotRepository,
    SqlObservedStateRepository,
    SqlOperationRepository,
    SqlOutboxRepository,
    SqlProjectMemberRepository,
    SqlProjectQuotaRepository,
    SqlProjectRepository,
    SqlQosPolicyRepository,
    SqlResourceSnapshotRepository,
    SqlRetentionPolicyRepository,
    SqlRouterRepository,
    SqlSecurityGroupMemberRepository,
    SqlSecurityGroupRepository,
    SqlSecurityPolicyRepository,
    SqlServiceAccountRepository,
    SqlServiceObjectRepository,
    SqlServiceTokenRepository,
    SqlTrunkPortRepository,
    SqlWebhookSubscriptionRepository,
)

__all__ = [
    "Base",
    "SqlAddressPoolRepository",
    "SqlAuditEventRepository",
    "SqlBgpPeerRepository",
    "SqlEnrollmentTokenRepository",
    "SqlFloatingIpRepository",
    "SqlGatewayBondRepository",
    "SqlHealthMonitorRepository",
    "SqlIpAllocationRepository",
    "SqlLbListenerRepository",
    "SqlLbMemberRepository",
    "SqlLbPoolRepository",
    "SqlLoadBalancerRepository",
    "SqlLogicalPortRepository",
    "SqlNetworkRepository",
    "SqlNodeRepository",
    "SqlNodeSnapshotRepository",
    "SqlObservedStateRepository",
    "SqlOperationRepository",
    "SqlOutboxRepository",
    "SqlProjectMemberRepository",
    "SqlProjectQuotaRepository",
    "SqlProjectRepository",
    "SqlQosPolicyRepository",
    "SqlResourceSnapshotRepository",
    "SqlRetentionPolicyRepository",
    "SqlRouterRepository",
    "SqlSecurityGroupMemberRepository",
    "SqlSecurityGroupRepository",
    "SqlSecurityPolicyRepository",
    "SqlServiceAccountRepository",
    "SqlServiceObjectRepository",
    "SqlServiceTokenRepository",
    "SqlTrunkPortRepository",
    "SqlWebhookSubscriptionRepository",
    "build_engine",
    "build_sessionmaker",
]
