"""Persistence ports.

We expose **one repository per aggregate**. Each repository hides storage
specifics — the same protocol is satisfied by the in-memory adapter (used in
tests and quick dev loops) and by the SQLAlchemy adapter (production /
durable MVP).
"""

from __future__ import annotations

from typing import Protocol

from sdn_controller.core.entities import (
    EnrollmentToken,
    IpAllocation,
    Network,
    Node,
    ObservedState,
    Operation,
    OperationEvent,
)
from sdn_controller.core.value_objects.enums import OperationStatus
from sdn_controller.core.value_objects.ids import (
    EnrollmentTokenId,
    IpAllocationId,
    NetworkId,
    NodeId,
    OperationId,
    SubnetId,
)
from sdn_controller.core.value_objects.ipam import OwnerRef


class NodeRepository(Protocol):
    async def get(self, node_id: NodeId) -> Node | None: ...
    async def get_by_name(self, name: str) -> Node | None: ...
    async def list(self) -> list[Node]: ...
    async def save(self, node: Node) -> None: ...
    async def delete(self, node_id: NodeId) -> None: ...


class NetworkRepository(Protocol):
    async def get(self, network_id: NetworkId) -> Network | None: ...
    async def get_by_name(self, name: str) -> Network | None: ...
    async def get_by_subnet_id(self, subnet_id: SubnetId) -> Network | None: ...
    async def list(self) -> list[Network]: ...
    async def save(self, network: Network) -> None: ...
    async def delete(self, network_id: NetworkId) -> None: ...


class OperationRepository(Protocol):
    async def get(self, operation_id: OperationId) -> Operation | None: ...
    async def list(self, *, limit: int = 100) -> list[Operation]: ...
    async def save(self, operation: Operation) -> None: ...
    async def update_status(
        self,
        operation_id: OperationId,
        status: OperationStatus,
        event: OperationEvent,
    ) -> None: ...


class EnrollmentTokenRepository(Protocol):
    async def get(self, token_id: EnrollmentTokenId) -> EnrollmentToken | None: ...
    async def get_by_hash(self, token_hash: str) -> EnrollmentToken | None: ...
    async def list_for_node(self, node_id: NodeId) -> list[EnrollmentToken]: ...
    async def save(self, token: EnrollmentToken) -> None: ...
    async def delete_for_node(self, node_id: NodeId) -> None: ...


class ObservedStateRepository(Protocol):
    """Per-node cache of the most recent OVS state we observed."""

    async def get(self, node_id: NodeId) -> ObservedState | None: ...
    async def save(self, state: ObservedState) -> None: ...
    async def delete(self, node_id: NodeId) -> None: ...


class IpAllocationRepository(Protocol):
    """IPAM allocations keyed by id; queries by subnet, by address, by owner."""

    async def get(self, allocation_id: IpAllocationId) -> IpAllocation | None: ...
    async def get_by_address(self, subnet_id: SubnetId, address: str) -> IpAllocation | None: ...
    async def list_for_subnet(self, subnet_id: SubnetId) -> list[IpAllocation]: ...
    async def list_for_owner(self, owner: OwnerRef) -> list[IpAllocation]: ...
    async def save(self, allocation: IpAllocation) -> None: ...
    async def delete(self, allocation_id: IpAllocationId) -> None: ...
