"""Persistence ports.

We expose **one repository per aggregate**. Each repository hides storage
specifics — the same protocol is satisfied by the in-memory adapter (used in
tests and quick dev loops) and by the SQLAlchemy adapter (production /
durable MVP).
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from sdn_controller.core.entities import (
    AddressPool,
    AuditEvent,
    BgpPeer,
    EnrollmentToken,
    FloatingIP,
    IpAllocation,
    LogicalPort,
    Network,
    Node,
    NodeSnapshot,
    ObservedState,
    Operation,
    OperationEvent,
    OutboxEvent,
    Project,
    ProjectMember,
    QosPolicy,
    Router,
    SecurityGroup,
    SecurityGroupMember,
    SecurityPolicy,
    ServiceAccount,
    ServiceObject,
    ServiceToken,
    TrunkPort,
    WebhookSubscription,
)
from sdn_controller.core.value_objects.enums import OperationStatus  # noqa: F401
from sdn_controller.core.value_objects.ids import (
    AddressPoolId,
    AuditEventId,
    EnrollmentTokenId,
    IpAllocationId,
    LogicalPortId,
    NetworkId,
    NodeId,
    NodeSnapshotId,
    OperationId,
    OutboxEventId,
    ProjectId,
    QosPolicyId,
    SecurityGroupId,
    SecurityPolicyId,
    ServiceAccountId,
    ServiceObjectId,
    ServiceTokenId,
    SubnetId,
    BgpPeerId,
    FloatingIpId,
    RouterId,
    TrunkPortId,
    WebhookSubscriptionId,
)
from sdn_controller.core.value_objects.ipam import OwnerRef
from sdn_controller.core.value_objects.security import Role


class NodeRepository(Protocol):
    async def get(self, node_id: NodeId) -> Node | None: ...
    async def get_by_name(self, name: str) -> Node | None: ...
    async def list(self) -> list[Node]: ...
    async def save(self, node: Node) -> None: ...
    async def delete(self, node_id: NodeId) -> None: ...


class NetworkRepository(Protocol):
    async def get(self, network_id: NetworkId) -> Network | None: ...
    async def get_by_name(self, name: str) -> Network | None: ...
    async def get_by_subnet_id(self, subnet_id: SubnetId) -> Network | None: ...
    async def list(self) -> list[Network]: ...
    async def save(self, network: Network) -> None: ...
    async def delete(self, network_id: NetworkId) -> None: ...


class OperationRepository(Protocol):
    async def get(self, operation_id: OperationId) -> Operation | None: ...
    async def list(self, *, limit: int = 100) -> list[Operation]: ...
    async def save(self, operation: Operation) -> None: ...
    async def update_status(
        self,
        operation_id: OperationId,
        status: OperationStatus,
        event: OperationEvent,
    ) -> None: ...
    async def delete_terminal_before(self, cutoff: datetime) -> int: ...


class EnrollmentTokenRepository(Protocol):
    async def get(self, token_id: EnrollmentTokenId) -> EnrollmentToken | None: ...
    async def get_by_hash(self, token_hash: str) -> EnrollmentToken | None: ...
    async def list_for_node(self, node_id: NodeId) -> list[EnrollmentToken]: ...
    async def save(self, token: EnrollmentToken) -> None: ...
    async def delete_for_node(self, node_id: NodeId) -> None: ...


class ObservedStateRepository(Protocol):
    """Per-node cache of the most recent OVS state we observed."""

    async def get(self, node_id: NodeId) -> ObservedState | None: ...
    async def save(self, state: ObservedState) -> None: ...
    async def delete(self, node_id: NodeId) -> None: ...


class IpAllocationRepository(Protocol):
    """IPAM allocations keyed by id; queries by subnet, by address, by owner."""

    async def get(self, allocation_id: IpAllocationId) -> IpAllocation | None: ...
    async def get_by_address(self, subnet_id: SubnetId, address: str) -> IpAllocation | None: ...
    async def list_for_subnet(self, subnet_id: SubnetId) -> list[IpAllocation]: ...
    async def list_for_owner(self, owner: OwnerRef) -> list[IpAllocation]: ...
    async def save(self, allocation: IpAllocation) -> None: ...
    async def delete(self, allocation_id: IpAllocationId) -> None: ...


class ServiceAccountRepository(Protocol):
    """Сервисные аккаунты (M9 — SDN-028/030)."""

    async def get(self, account_id: ServiceAccountId) -> ServiceAccount | None: ...
    async def get_by_name(self, name: str) -> ServiceAccount | None: ...
    async def list(self) -> list[ServiceAccount]: ...
    async def save(self, account: ServiceAccount) -> None: ...


class ServiceTokenRepository(Protocol):
    """Токены сервисных аккаунтов. Поиск по хэшу — горячий путь
    аутентификации каждого запроса; индекс на ``token_hash`` обязателен."""

    async def get(self, token_id: ServiceTokenId) -> ServiceToken | None: ...
    async def get_by_hash(self, token_hash: str) -> ServiceToken | None: ...
    async def list_for_account(self, account_id: ServiceAccountId) -> list[ServiceToken]: ...
    async def save(self, token: ServiceToken) -> None: ...


class NodeSnapshotRepository(Protocol):
    """Каталог снапшотов узлов (M11). ``save`` идемпотентен по id,
    ``delete`` удаляет запись (агент-side snapshot отзывается отдельно)."""

    async def save(self, snapshot: NodeSnapshot) -> None: ...
    async def get(self, snapshot_id: NodeSnapshotId) -> NodeSnapshot | None: ...
    async def list_for_node(self, node_id: NodeId) -> list[NodeSnapshot]: ...
    async def list(self, *, limit: int = 200) -> list[NodeSnapshot]: ...
    async def delete(self, snapshot_id: NodeSnapshotId) -> None: ...


class AuditEventRepository(Protocol):
    """Append-only журнал. ``save`` — единственная операция записи;
    ``list`` отдаёт срез по фильтрам в обратном хронологическом порядке."""

    async def save(self, event: AuditEvent) -> None: ...
    async def get(self, event_id: AuditEventId) -> AuditEvent | None: ...
    async def list(
        self,
        *,
        actor: str | None = None,
        action: str | None = None,
        resource_type: str | None = None,
        resource_id: str | None = None,
        since: datetime | None = None,
        limit: int = 100,
    ) -> list[AuditEvent]: ...

    async def list_before(self, cutoff: datetime, *, limit: int = 1000) -> Sequence[AuditEvent]: ...
    async def delete_before(self, cutoff: datetime) -> int: ...
    async def delete_many(self, event_ids: Sequence[AuditEventId]) -> int: ...


class OutboxRepository(Protocol):
    """Transactional outbox (SDN-055).

    ``append`` присваивает событию монотонный ``event_id`` (autoincrement
    в SQL, счётчик в памяти) и возвращает уже materialized-объект:
    подписчик использует ``event_id`` как watermark.

    ``list_since`` отдаёт срез событий с ``event_id > since``; этим
    пользуется и dispatcher (webhook'и), и snapshot-export ручка.
    """

    async def append(self, event: OutboxEvent) -> OutboxEvent: ...
    async def get(self, event_id: OutboxEventId) -> OutboxEvent | None: ...
    async def list_since(self, *, since: int = 0, limit: int = 200) -> Sequence[OutboxEvent]: ...
    async def list_undelivered(self, *, limit: int = 200) -> Sequence[OutboxEvent]: ...
    async def mark_delivered(self, event_ids: Sequence[OutboxEventId], *, at: datetime) -> None: ...
    async def head_event_id(self) -> int: ...
    async def delete_delivered_before(self, cutoff: datetime) -> int: ...


class WebhookSubscriptionRepository(Protocol):
    """Подписки на outbox-события (SDN-054).

    ``save`` идемпотентен по id. ``list_active`` отдаёт подписки в
    состоянии ``active`` (dispatcher гоняет их). Метаданные доставки
    (cursor, failure_count, last_*) тоже идут через ``save``, чтобы
    репа оставалась узкой по поверхности.
    """

    async def save(self, subscription: WebhookSubscription) -> None: ...
    async def get(self, sub_id: WebhookSubscriptionId) -> WebhookSubscription | None: ...
    async def list(self) -> Sequence[WebhookSubscription]: ...
    async def list_active(self) -> Sequence[WebhookSubscription]: ...
    async def delete(self, sub_id: WebhookSubscriptionId) -> None: ...


class ProjectRepository(Protocol):
    """Проекты (N0 — мультитенантность)."""

    async def get(self, project_id: ProjectId) -> Project | None: ...
    async def get_by_slug(self, slug: str) -> Project | None: ...
    async def list(self) -> list[Project]: ...
    async def save(self, project: Project) -> None: ...
    async def delete(self, project_id: ProjectId) -> None: ...


class ProjectMemberRepository(Protocol):
    """Членство сервисных аккаунтов в проектах (N0)."""

    async def get(
        self, project_id: ProjectId, sa_id: ServiceAccountId
    ) -> ProjectMember | None: ...
    async def list_for_project(self, project_id: ProjectId) -> list[ProjectMember]: ...
    async def list_for_account(self, sa_id: ServiceAccountId) -> list[ProjectMember]: ...
    async def save(self, member: ProjectMember) -> None: ...
    async def delete(self, project_id: ProjectId, sa_id: ServiceAccountId) -> None: ...
    async def has_role(
        self, project_id: ProjectId, sa_id: ServiceAccountId, role: Role
    ) -> bool: ...


# ---------------------------------------------------------------------------
# N1 repositories
# ---------------------------------------------------------------------------


class LogicalPortRepository(Protocol):
    """Logical ports (N1-01)."""

    async def get(self, port_id: LogicalPortId) -> LogicalPort | None: ...
    async def list(
        self,
        *,
        node_id: NodeId | None = None,
        network_id: NetworkId | None = None,
        project_id: ProjectId | None = None,
    ) -> list[LogicalPort]: ...
    async def save(self, port: LogicalPort) -> None: ...
    async def delete(self, port_id: LogicalPortId) -> None: ...
    async def delete_for_node(self, node_id: NodeId) -> None: ...


class SecurityGroupRepository(Protocol):
    """Security groups (N1-02)."""

    async def get(self, sg_id: SecurityGroupId) -> SecurityGroup | None: ...
    async def list(self, *, project_id: ProjectId | None = None) -> list[SecurityGroup]: ...
    async def save(self, sg: SecurityGroup) -> None: ...
    async def delete(self, sg_id: SecurityGroupId) -> None: ...


class SecurityGroupMemberRepository(Protocol):
    """Members of security groups (N1-02)."""

    async def list_for_group(self, sg_id: SecurityGroupId) -> list[SecurityGroupMember]: ...
    async def add(self, member: SecurityGroupMember) -> None: ...
    async def remove(
        self,
        sg_id: SecurityGroupId,
        member_type: str,
        member_value: str,
    ) -> None: ...
    async def delete_for_group(self, sg_id: SecurityGroupId) -> None: ...


class AddressPoolRepository(Protocol):
    """Address pools (N1-03)."""

    async def get(self, pool_id: AddressPoolId) -> AddressPool | None: ...
    async def list(self, *, project_id: ProjectId | None = None) -> list[AddressPool]: ...
    async def save(self, pool: AddressPool) -> None: ...
    async def delete(self, pool_id: AddressPoolId) -> None: ...


class ServiceObjectRepository(Protocol):
    """Service objects (N1-04)."""

    async def get(self, obj_id: ServiceObjectId) -> ServiceObject | None: ...
    async def list(self, *, project_id: ProjectId | None = None) -> list[ServiceObject]: ...
    async def save(self, obj: ServiceObject) -> None: ...
    async def delete(self, obj_id: ServiceObjectId) -> None: ...


class QosPolicyRepository(Protocol):
    """QoS policies (N1-05)."""

    async def get(self, policy_id: QosPolicyId) -> QosPolicy | None: ...
    async def list(self, *, project_id: ProjectId | None = None) -> list[QosPolicy]: ...
    async def save(self, policy: QosPolicy) -> None: ...
    async def delete(self, policy_id: QosPolicyId) -> None: ...


# ---------------------------------------------------------------------------
# N2 — SecurityPolicy + TrunkPort
# ---------------------------------------------------------------------------


class SecurityPolicyRepository(Protocol):
    """Политики безопасности (N2-01)."""

    async def get(self, policy_id: SecurityPolicyId) -> SecurityPolicy | None: ...
    async def list(self, *, project_id: ProjectId | None = None) -> list[SecurityPolicy]: ...
    async def save(self, policy: SecurityPolicy) -> None: ...
    async def delete(self, policy_id: SecurityPolicyId) -> None: ...


class TrunkPortRepository(Protocol):
    """Транковые порты 802.1q (N2-05)."""

    async def get(self, port_id: TrunkPortId) -> TrunkPort | None: ...
    async def list(
        self,
        *,
        node_id: NodeId | None = None,
        project_id: ProjectId | None = None,
    ) -> list[TrunkPort]: ...
    async def save(self, port: TrunkPort) -> None: ...
    async def delete(self, port_id: TrunkPortId) -> None: ...


# ---------------------------------------------------------------------------
# N3 — Router / FloatingIP / BgpPeer
# ---------------------------------------------------------------------------


class RouterRepository(Protocol):
    """L3-маршрутизаторы (N3-01)."""

    async def get(self, router_id: RouterId) -> Router | None: ...
    async def list(self, *, project_id: ProjectId | None = None) -> list[Router]: ...
    async def save(self, router: Router) -> None: ...
    async def delete(self, router_id: RouterId) -> None: ...


class FloatingIpRepository(Protocol):
    """Floating IP-адреса (N3-02)."""

    async def get(self, fip_id: FloatingIpId) -> FloatingIP | None: ...
    async def list(
        self,
        *,
        project_id: ProjectId | None = None,
        router_id: RouterId | None = None,
    ) -> list[FloatingIP]: ...
    async def save(self, fip: FloatingIP) -> None: ...
    async def delete(self, fip_id: FloatingIpId) -> None: ...


class BgpPeerRepository(Protocol):
    """BGP-пиры маршрутизаторов (N3-05)."""

    async def get(self, peer_id: BgpPeerId) -> BgpPeer | None: ...
    async def list(
        self,
        *,
        router_id: RouterId | None = None,
        project_id: ProjectId | None = None,
    ) -> list[BgpPeer]: ...
    async def save(self, peer: BgpPeer) -> None: ...
    async def delete(self, peer_id: BgpPeerId) -> None: ...
