"""Persistence ports.

We expose **one repository per aggregate**. Each repository hides storage
specifics — the same protocol is satisfied by the in-memory adapter (used in
tests and quick dev loops) and by the SQLAlchemy adapter (production /
durable MVP).
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from sdn_controller.core.entities import (
    AuditEvent,
    EnrollmentToken,
    IpAllocation,
    Network,
    Node,
    NodeSnapshot,
    ObservedState,
    Operation,
    OperationEvent,
    OutboxEvent,
    ServiceAccount,
    ServiceToken,
    WebhookSubscription,
)
from sdn_controller.core.value_objects.enums import OperationStatus
from sdn_controller.core.value_objects.ids import (
    AuditEventId,
    EnrollmentTokenId,
    IpAllocationId,
    NetworkId,
    NodeId,
    NodeSnapshotId,
    OperationId,
    OutboxEventId,
    ServiceAccountId,
    ServiceTokenId,
    SubnetId,
    WebhookSubscriptionId,
)
from sdn_controller.core.value_objects.ipam import OwnerRef


class NodeRepository(Protocol):
    async def get(self, node_id: NodeId) -> Node | None: ...
    async def get_by_name(self, name: str) -> Node | None: ...
    async def list(self) -> list[Node]: ...
    async def save(self, node: Node) -> None: ...
    async def delete(self, node_id: NodeId) -> None: ...


class NetworkRepository(Protocol):
    async def get(self, network_id: NetworkId) -> Network | None: ...
    async def get_by_name(self, name: str) -> Network | None: ...
    async def get_by_subnet_id(self, subnet_id: SubnetId) -> Network | None: ...
    async def list(self) -> list[Network]: ...
    async def save(self, network: Network) -> None: ...
    async def delete(self, network_id: NetworkId) -> None: ...


class OperationRepository(Protocol):
    async def get(self, operation_id: OperationId) -> Operation | None: ...
    async def list(self, *, limit: int = 100) -> list[Operation]: ...
    async def save(self, operation: Operation) -> None: ...
    async def update_status(
        self,
        operation_id: OperationId,
        status: OperationStatus,
        event: OperationEvent,
    ) -> None: ...
    async def delete_terminal_before(self, cutoff: datetime) -> int: ...


class EnrollmentTokenRepository(Protocol):
    async def get(self, token_id: EnrollmentTokenId) -> EnrollmentToken | None: ...
    async def get_by_hash(self, token_hash: str) -> EnrollmentToken | None: ...
    async def list_for_node(self, node_id: NodeId) -> list[EnrollmentToken]: ...
    async def save(self, token: EnrollmentToken) -> None: ...
    async def delete_for_node(self, node_id: NodeId) -> None: ...


class ObservedStateRepository(Protocol):
    """Per-node cache of the most recent OVS state we observed."""

    async def get(self, node_id: NodeId) -> ObservedState | None: ...
    async def save(self, state: ObservedState) -> None: ...
    async def delete(self, node_id: NodeId) -> None: ...


class IpAllocationRepository(Protocol):
    """IPAM allocations keyed by id; queries by subnet, by address, by owner."""

    async def get(self, allocation_id: IpAllocationId) -> IpAllocation | None: ...
    async def get_by_address(self, subnet_id: SubnetId, address: str) -> IpAllocation | None: ...
    async def list_for_subnet(self, subnet_id: SubnetId) -> list[IpAllocation]: ...
    async def list_for_owner(self, owner: OwnerRef) -> list[IpAllocation]: ...
    async def save(self, allocation: IpAllocation) -> None: ...
    async def delete(self, allocation_id: IpAllocationId) -> None: ...


class ServiceAccountRepository(Protocol):
    """Сервисные аккаунты (M9 — SDN-028/030)."""

    async def get(self, account_id: ServiceAccountId) -> ServiceAccount | None: ...
    async def get_by_name(self, name: str) -> ServiceAccount | None: ...
    async def list(self) -> list[ServiceAccount]: ...
    async def save(self, account: ServiceAccount) -> None: ...


class ServiceTokenRepository(Protocol):
    """Токены сервисных аккаунтов. Поиск по хэшу — горячий путь
    аутентификации каждого запроса; индекс на ``token_hash`` обязателен."""

    async def get(self, token_id: ServiceTokenId) -> ServiceToken | None: ...
    async def get_by_hash(self, token_hash: str) -> ServiceToken | None: ...
    async def list_for_account(self, account_id: ServiceAccountId) -> list[ServiceToken]: ...
    async def save(self, token: ServiceToken) -> None: ...


class NodeSnapshotRepository(Protocol):
    """Каталог снапшотов узлов (M11). ``save`` идемпотентен по id,
    ``delete`` удаляет запись (агент-side snapshot отзывается отдельно)."""

    async def save(self, snapshot: NodeSnapshot) -> None: ...
    async def get(self, snapshot_id: NodeSnapshotId) -> NodeSnapshot | None: ...
    async def list_for_node(self, node_id: NodeId) -> list[NodeSnapshot]: ...
    async def list(self, *, limit: int = 200) -> list[NodeSnapshot]: ...
    async def delete(self, snapshot_id: NodeSnapshotId) -> None: ...


class AuditEventRepository(Protocol):
    """Append-only журнал. ``save`` — единственная операция записи;
    ``list`` отдаёт срез по фильтрам в обратном хронологическом порядке."""

    async def save(self, event: AuditEvent) -> None: ...
    async def get(self, event_id: AuditEventId) -> AuditEvent | None: ...
    async def list(
        self,
        *,
        actor: str | None = None,
        action: str | None = None,
        resource_type: str | None = None,
        resource_id: str | None = None,
        since: datetime | None = None,
        limit: int = 100,
    ) -> list[AuditEvent]: ...

    async def list_before(self, cutoff: datetime, *, limit: int = 1000) -> Sequence[AuditEvent]: ...
    async def delete_before(self, cutoff: datetime) -> int: ...
    async def delete_many(self, event_ids: Sequence[AuditEventId]) -> int: ...


class OutboxRepository(Protocol):
    """Transactional outbox (SDN-055).

    ``append`` присваивает событию монотонный ``event_id`` (autoincrement
    в SQL, счётчик в памяти) и возвращает уже materialized-объект:
    подписчик использует ``event_id`` как watermark.

    ``list_since`` отдаёт срез событий с ``event_id > since``; этим
    пользуется и dispatcher (webhook'и), и snapshot-export ручка.
    """

    async def append(self, event: OutboxEvent) -> OutboxEvent: ...
    async def get(self, event_id: OutboxEventId) -> OutboxEvent | None: ...
    async def list_since(self, *, since: int = 0, limit: int = 200) -> Sequence[OutboxEvent]: ...
    async def list_undelivered(self, *, limit: int = 200) -> Sequence[OutboxEvent]: ...
    async def mark_delivered(self, event_ids: Sequence[OutboxEventId], *, at: datetime) -> None: ...
    async def head_event_id(self) -> int: ...
    async def delete_delivered_before(self, cutoff: datetime) -> int: ...


class WebhookSubscriptionRepository(Protocol):
    """Подписки на outbox-события (SDN-054).

    ``save`` идемпотентен по id. ``list_active`` отдаёт подписки в
    состоянии ``active`` (dispatcher гоняет их). Метаданные доставки
    (cursor, failure_count, last_*) тоже идут через ``save``, чтобы
    репа оставалась узкой по поверхности.
    """

    async def save(self, subscription: WebhookSubscription) -> None: ...
    async def get(self, sub_id: WebhookSubscriptionId) -> WebhookSubscription | None: ...
    async def list(self) -> Sequence[WebhookSubscription]: ...
    async def list_active(self) -> Sequence[WebhookSubscription]: ...
    async def delete(self, sub_id: WebhookSubscriptionId) -> None: ...
